### ISSUE TITLE
bug: `simplifyBaseIAMLogGroups` function is not taking others statements used in the iam role definition

### ISSUE THREAD

**Issue by frangeris** [shelfio/serverless-simplify-default-exec-role-plugin#5]
Hi there, quick issue report

The function that rewrite the `Statement` is discarting any other permissions being used and previously defined, only the logs actions are being attached:

```json
"Action": [
  "logs:CreateLogStream",
  "logs:CreateLogGroup",
  "logs:PutLogEvents"
],
```

I have others required permissions that are not included in the final policy:

```yml
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "cloudwatch:*"
            - "logs:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"
        - Effect: Allow
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParametersByPath"
            - "ssm:PutParameter"
            - "ssm:DescribeParameters"
          Resource: "*"
        - Effect: Allow
          Action:
            - "events:PutEvents"
          Resource: "*"
```
